-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Copy / Paste

hl.bind("SUPER" .. " + " .. "C", hl.dsp.send_shortcut("CTRL", "Insert"))

hl.bind("SUPER" .. " + " .. "V", hl.dsp.send_shortcut("SHIFT", "Insert"))

hl.bind("SUPER" .. " + " .. "X", hl.dsp.send_shortcut("CTRL", "X"))

hl.bind("SUPER + CTRL" .. " + " .. "V", hl.dsp.exec_cmd("omarchy-launch-walker -m clipboard"))
