-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Only display the OSD on the currently focused monitor

local osdclient = "swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

-- Laptop multimedia keys for volume and LCD brightness (with OSD)

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --output-volume raise"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --output-volume lower"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --output-volume mute-toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --input-volume mute-toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --brightness raise"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --brightness lower"), { locked = true })

-- Precise 1% multimedia adjustments with Alt modifier

hl.bind("ALT" .. " + " .. "XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --output-volume +1"), { locked = true })

hl.bind("ALT" .. " + " .. "XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --output-volume -1"), { locked = true })

hl.bind("ALT" .. " + " .. "XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --brightness +1"), { locked = true })

hl.bind("ALT" .. " + " .. "XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --brightness -1"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("swayosd-client --monitor $(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name') --playerctl previous"), { locked = true })

-- Switch audio output with Super + Mute

hl.bind("SUPER" .. " + " .. "XF86AudioMute", hl.dsp.exec_cmd("omarchy-cmd-audio-switch"), { locked = true })
