-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is now a deprecated file meant for those who did not wish to learn the latest Omarchy hotkeys.

-- Do not make changes here, but bring them to tiling-v2.conf instead.

-- Close windows

hl.bind("SUPER" .. " + " .. "W", hl.dsp.window.close())

hl.bind("CTRL + ALT" .. " + " .. "DELETE", hl.dsp.exec_cmd("omarchy-hyprland-window-close-all"))

-- Control tiling

hl.bind("SUPER" .. " + " .. "J", hl.dsp.layout(nil))

-- dwindle

hl.bind("SUPER" .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind("SUPER + SHIFT" .. " + " .. "V", hl.dsp.window.float())

hl.bind("SHIFT" .. " + " .. "F11", hl.dsp.window.fullscreen())

hl.bind("ALT" .. " + " .. "F11", hl.dsp.window.fullscreen())

-- Move focus with SUPER + arrow keys

hl.bind("SUPER" .. " + " .. "LEFT", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER" .. " + " .. "RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER" .. " + " .. "UP", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER" .. " + " .. "DOWN", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with SUPER + [0-9]

hl.bind("SUPER" .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER" .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER" .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER" .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER" .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER" .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER" .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

hl.bind("SUPER" .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

hl.bind("SUPER" .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

hl.bind("SUPER" .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with SUPER + SHIFT + [0-9]

hl.bind("SUPER + SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

-- TAB between workspaces

hl.bind("SUPER" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER + SHIFT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + CTRL" .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- Swap active window with the one next to it with SUPER + SHIFT + arrow keys

hl.bind("SUPER + SHIFT" .. " + " .. "LEFT", hl.dsp.window.swap({ direction = "left" }))

hl.bind("SUPER + SHIFT" .. " + " .. "RIGHT", hl.dsp.window.swap({ direction = "right" }))

hl.bind("SUPER + SHIFT" .. " + " .. "UP", hl.dsp.window.swap({ direction = "up" }))

hl.bind("SUPER + SHIFT" .. " + " .. "DOWN", hl.dsp.window.swap({ direction = "down" }))

-- Cycle through applications on active workspace

hl.bind("ALT" .. " + " .. "TAB", hl.dsp.window.cycle_next())

hl.bind("ALT + SHIFT" .. " + " .. "TAB", hl.dsp.window.cycle_next({ next = false }))

-- TODO: manual review (unknown dispatcher: Reveal active window on top)
-- hl.bind("ALT + TAB", hl.dsp.Reveal active window on top("bringactivetotop"))

-- TODO: manual review (unknown dispatcher: Reveal active window on top)
-- hl.bind("ALT + SHIFT + TAB", hl.dsp.Reveal active window on top("bringactivetotop"))

-- Resize active window

-- TODO: manual review (unknown dispatcher: Expand window left)
-- hl.bind("SUPER + code:20", hl.dsp.Expand window left("resizeactive", "-100 0"))

-- - key

-- TODO: manual review (unknown dispatcher: Shrink window left)
-- hl.bind("SUPER + code:21", hl.dsp.Shrink window left("resizeactive", "100 0"))

-- = key

-- TODO: manual review (unknown dispatcher: Shrink window up)
-- hl.bind("SUPER + SHIFT + code:20", hl.dsp.Shrink window up("resizeactive", "0 -100"))

-- TODO: manual review (unknown dispatcher: Expand window down)
-- hl.bind("SUPER + SHIFT + code:21", hl.dsp.Expand window down("resizeactive", "0 100"))

-- Scroll through existing workspaces with SUPER + scroll

hl.bind("SUPER" .. " + " .. "MOUSE_DOWN", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER" .. " + " .. "MOUSE_UP", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind("SUPER" .. " + " .. "mouse:272", nil, { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })
