-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Close windows

hl.bind("SUPER" .. " + " .. "W", hl.dsp.window.close())

hl.bind("CTRL + ALT" .. " + " .. "DELETE", hl.dsp.exec_cmd("omarchy-hyprland-window-close-all"))

-- Control tiling

hl.bind("SUPER" .. " + " .. "J", hl.dsp.layout(nil))

-- dwindle

hl.bind("SUPER" .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind("SUPER" .. " + " .. "T", hl.dsp.window.float())

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind("SUPER + CTRL" .. " + " .. "F", hl.dsp.window.fullscreen_state("0 2"))

hl.bind("SUPER + ALT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind("SUPER" .. " + " .. "O", hl.dsp.exec_cmd("omarchy-hyprland-window-pop"))

-- Move focus with SUPER + arrow keys

hl.bind("SUPER" .. " + " .. "LEFT", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER" .. " + " .. "RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER" .. " + " .. "UP", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER" .. " + " .. "DOWN", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with SUPER + [1-9; 0]

hl.bind("SUPER" .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER" .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER" .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER" .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER" .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER" .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER" .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

hl.bind("SUPER" .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

hl.bind("SUPER" .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

hl.bind("SUPER" .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with SUPER + SHIFT + [1-9; 0]

hl.bind("SUPER + SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

-- Move active window silently to a workspace with SUPER + SHIFT + ALT + [1-9; 0]

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- Control scratchpad

-- bindd = SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad

-- bindd = SUPER ALT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

-- TAB between workspaces

hl.bind("SUPER" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER + SHIFT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + CTRL" .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- Move workspaces to other monitors

-- TODO: manual review (unknown dispatcher: Move workspace to left monitor)
-- hl.bind("SUPER + SHIFT + ALT + LEFT", hl.dsp.Move workspace to left monitor("movecurrentworkspacetomonitor", "l"))

-- TODO: manual review (unknown dispatcher: Move workspace to right monitor)
-- hl.bind("SUPER + SHIFT + ALT + RIGHT", hl.dsp.Move workspace to right monitor("movecurrentworkspacetomonitor", "r"))

-- Swap active window with the one next to it with SUPER + SHIFT + arrow keys

hl.bind("SUPER + SHIFT" .. " + " .. "LEFT", hl.dsp.window.swap({ direction = "left" }))

hl.bind("SUPER + SHIFT" .. " + " .. "RIGHT", hl.dsp.window.swap({ direction = "right" }))

hl.bind("SUPER + SHIFT" .. " + " .. "UP", hl.dsp.window.swap({ direction = "up" }))

hl.bind("SUPER + SHIFT" .. " + " .. "DOWN", hl.dsp.window.swap({ direction = "down" }))

-- Cycle through applications on active workspace

hl.bind("ALT" .. " + " .. "TAB", hl.dsp.window.cycle_next())

hl.bind("ALT + SHIFT" .. " + " .. "TAB", hl.dsp.window.cycle_next({ next = false }))

-- TODO: manual review (unknown dispatcher: Reveal active window on top)
-- hl.bind("ALT + TAB", hl.dsp.Reveal active window on top("bringactivetotop"))

-- TODO: manual review (unknown dispatcher: Reveal active window on top)
-- hl.bind("ALT + SHIFT + TAB", hl.dsp.Reveal active window on top("bringactivetotop"))

-- Resize active window

-- TODO: manual review (unknown dispatcher: Expand window left)
-- hl.bind("SUPER + code:20", hl.dsp.Expand window left("resizeactive", "-100 0"))

-- - key

-- TODO: manual review (unknown dispatcher: Shrink window left)
-- hl.bind("SUPER + code:21", hl.dsp.Shrink window left("resizeactive", "100 0"))

-- = key

-- TODO: manual review (unknown dispatcher: Shrink window up)
-- hl.bind("SUPER + SHIFT + code:20", hl.dsp.Shrink window up("resizeactive", "0 -100"))

-- TODO: manual review (unknown dispatcher: Expand window down)
-- hl.bind("SUPER + SHIFT + code:21", hl.dsp.Expand window down("resizeactive", "0 100"))

-- Scroll through existing workspaces with SUPER + scroll

hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind("SUPER" .. " + " .. "mouse:272", nil, { mouse = true })

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })

-- Toggle groups

hl.bind("SUPER" .. " + " .. "G", hl.dsp.group.toggle())

hl.bind("SUPER + ALT" .. " + " .. "G", hl.dsp.window.move({ out_of_group = true }))

-- Join groups

hl.bind("SUPER + ALT" .. " + " .. "LEFT", hl.dsp.window.move({ into_group = "left" }))

hl.bind("SUPER + ALT" .. " + " .. "RIGHT", hl.dsp.window.move({ into_group = "right" }))

hl.bind("SUPER + ALT" .. " + " .. "UP", hl.dsp.window.move({ into_group = "up" }))

hl.bind("SUPER + ALT" .. " + " .. "DOWN", hl.dsp.window.move({ into_group = "down" }))

-- Navigate a single set of grouped windows

hl.bind("SUPER + ALT" .. " + " .. "TAB", hl.dsp.group.next())

hl.bind("SUPER + ALT + SHIFT" .. " + " .. "TAB", hl.dsp.group.next({ forward = false }))

-- Overload lateral window navigation for grouped windows

hl.bind("SUPER + ALT" .. " + " .. "LEFT", hl.dsp.group.next({ forward = false }))

hl.bind("SUPER + ALT" .. " + " .. "RIGHT", hl.dsp.group.next())

-- Scroll through a set of grouped windows with SUPER + ALT + scroll

hl.bind("SUPER + ALT" .. " + " .. "mouse_down", hl.dsp.group.next())

hl.bind("SUPER + ALT" .. " + " .. "mouse_up", hl.dsp.group.next({ forward = false }))

-- Activate window in a group by number

hl.bind("SUPER + ALT" .. " + " .. "code:10", hl.dsp.group.next({ forward = false }))

hl.bind("SUPER + ALT" .. " + " .. "code:11", hl.dsp.group.next({ forward = false }))

hl.bind("SUPER + ALT" .. " + " .. "code:12", hl.dsp.group.next({ forward = false }))

hl.bind("SUPER + ALT" .. " + " .. "code:13", hl.dsp.group.next({ forward = false }))

hl.bind("SUPER + ALT" .. " + " .. "code:14", hl.dsp.group.next({ forward = false }))
