-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Menus

hl.bind("SUPER" .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-launch-walker"))

hl.bind("SUPER + CTRL" .. " + " .. "E", hl.dsp.exec_cmd("omarchy-launch-walker -m symbols"))

hl.bind("SUPER + ALT" .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-menu"))

hl.bind("SUPER" .. " + " .. "ESCAPE", hl.dsp.exec_cmd("omarchy-menu system"))

hl.bind("XF86PowerOff", hl.dsp.exec_cmd("omarchy-menu system"), { locked = true })

hl.bind("SUPER" .. " + " .. "K", hl.dsp.exec_cmd("omarchy-menu-keybindings"))

hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"))

-- Aesthetics

hl.bind("SUPER + SHIFT" .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-toggle-waybar"))

hl.bind("SUPER + CTRL" .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-theme-bg-next"))

hl.bind("SUPER + SHIFT + CTRL" .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-menu theme"))

hl.bind("SUPER" .. " + " .. "BACKSPACE", hl.dsp.exec_cmd("hyprctl dispatch setprop address:$(hyprctl activewindow -j | jq -r '.address') opaque toggle"))

hl.bind("SUPER + SHIFT" .. " + " .. "BACKSPACE", hl.dsp.exec_cmd("omarchy-hyprland-workspace-toggle-gaps"))

-- Notifications

hl.bind("SUPER" .. " + " .. "COMMA", hl.dsp.exec_cmd("makoctl dismiss"))

hl.bind("SUPER + SHIFT" .. " + " .. "COMMA", hl.dsp.exec_cmd("makoctl dismiss --all"))

hl.bind("SUPER + CTRL" .. " + " .. "COMMA", hl.dsp.exec_cmd("makoctl mode -t do-not-disturb && makoctl mode| grep -q 'do-not-disturb' && notify-send Silenced notifications || notify-send Enabled notifications"))

hl.bind("SUPER + ALT" .. " + " .. "COMMA", hl.dsp.exec_cmd("makoctl invoke"))

hl.bind("SUPER + SHIFT + ALT" .. " + " .. "COMMA", hl.dsp.exec_cmd("makoctl restore"))

-- Toggle idling

hl.bind("SUPER + CTRL" .. " + " .. "I", hl.dsp.exec_cmd("omarchy-toggle-idle"))

-- Toggle nightlight

hl.bind("SUPER + CTRL" .. " + " .. "N", hl.dsp.exec_cmd("omarchy-toggle-nightlight"))

-- Control Apple Display brightness

hl.bind("CTRL" .. " + " .. "F1", hl.dsp.exec_cmd("omarchy-cmd-apple-display-brightness -5000"))

hl.bind("CTRL" .. " + " .. "F2", hl.dsp.exec_cmd("omarchy-cmd-apple-display-brightness +5000"))

hl.bind("SHIFT + CTRL" .. " + " .. "F2", hl.dsp.exec_cmd("omarchy-cmd-apple-display-brightness +60000"))

-- Captures

hl.bind("PRINT", hl.dsp.exec_cmd("omarchy-cmd-screenshot"))

hl.bind("SHIFT" .. " + " .. "PRINT", hl.dsp.exec_cmd("omarchy-cmd-screenshot smart clipboard"))

hl.bind("ALT" .. " + " .. "PRINT", hl.dsp.exec_cmd("omarchy-menu screenrecord"))

hl.bind("SUPER" .. " + " .. "PRINT", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"))

-- File sharing

hl.bind("SUPER + CTRL" .. " + " .. "S", hl.dsp.exec_cmd("omarchy-menu share"))

-- Waybar-less information

hl.bind("SUPER + CTRL" .. " + " .. "T", hl.dsp.exec_cmd("notify-send     $(date + %A %H:%M — %d %B W%V %Y )"))

hl.bind("SUPER + CTRL" .. " + " .. "B", hl.dsp.exec_cmd("notify-send 󰁹    Battery is at $(omarchy-battery-remaining)%"))
