-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Floating windows

hl.window_rule({
	name = "float_on",
	match = {
		tag = "floating-window",
	},
	float = true,
})

hl.window_rule({
	name = "center_on",
	match = {
		tag = "floating-window",
	},
	center = true,
})

hl.window_rule({
	name = "size_875_600",
	match = {
		tag = "floating-window",
	},
	size = "875 600",
})

hl.window_rule({
	name = "tag__floating-window",
	match = {
		class = "(org.omarchy.bluetui|org.omarchy.impala|org.omarchy.wiremix|org.omarchy.btop|org.omarchy.terminal|org.omarchy.bash|org.gnome.NautilusPreviewer|org.gnome.Evince|com.gabm.satty|Omarchy|About|TUI.float|imv|mpv|org.omarchy.calcure)",
	},
	float = true,
})

-- windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)

hl.window_rule({
	match = {
		class = "org.gnome.Calculator",
	},
	float = true,
})

-- No transparency on media windows

hl.window_rule({
	match = {
		class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$",
	},
	opacity = "1 1",
})

-- Popped window rounding

hl.window_rule({
	match = {
		tag = "pop",
	},
	rounding = 8,
})

hl.window_rule({
	match = {
		class = "(weather-tui)",
	},
	float = true,
	size = { "(monitor_w*0.7)", "(monitor_h*0.8)" },
	center = true,
})

-- Gazelle WiFi TUI - floating window like Impala

hl.window_rule({
	match = {
		initial_class = "Gazelle",
	},
	float = true,
	size = { "800", "600" },
	center = true,
})

hl.window_rule({
	match = {
		initial_class = "(protonvpn-app)",
	},
	float = true,
	size = { "600", "800" },
	center = true,
})
