-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        -- col.active_border = rgb(f9af4f)
        col = {
            active_border = "rgb(ce9178)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 4,
    },
})
