-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
local smw = require("plugins.split-monitor-workspaces")
local mainMod = "SUPER"

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- List current monitors and resolutions possible: hyprctl monitors

-- Format: monitor = [port], resolution, position, scale

-- Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.

-- env = GDK_SCALE,2

-- monitor=HDMI-A-1,3840x2160@60,-1920x0,2

hl.monitor({
	output = "HDMI-A-1",
	disabled = true,
})

-- monitor=DP-3, 1920x1080@60, 0x0, 1, cm, hdr, sdrbrightness, 1.5, sdrsaturation, 1.1

hl.monitor({
	output = "DP-3",
	mode = "1920x1080@60",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "DP-2",
	mode = "1920x1080@60",
	position = "1920x0",
	scale = 1,
})

--#################
--   Workspaces   #
--#################

smw.setup({
	workspace_count = 4,
	keep_focused = false,
	enable_notifications = false,
	enable_persistent_workspaces = true,
})

for i = 1, smw.get_amount_of_workspaces() do
	local n = tostring(i)
	hl.bind(mainMod .. " +" .. n, smw.workspace(n))
	-- Move the active window to the Nth workspace on the currently focused monitor silently (no focus change).
	hl.bind(
		mainMod .. " + SHIFT +" .. n,
		smw.move_to_workspace(n),
		{ description = "Move focused window to workspace " .. n }
	)
	hl.bind(
		mainMod .. " + SHIFT + ALT +" .. n,
		smw.move_to_workspace_silent(n),
		{ description = "Move focused window to workspace " .. n .. " silently" }
	)
end

hl.bind(
	"SUPER + CTRL + SHIFT + LEFT",
	hl.dsp.window.move({ monitor = "l" }),
	{ description = "Move focused window to left monitor" }
)
hl.bind(
	"SUPER + CTRL + SHIFT + RIGHT",
	hl.dsp.window.move({ monitor = "r" }),
	{ description = "Move focused window to right monitor" }
)

-- workspace cycling

hl.bind("SUPER + TAB", smw.cycle_workspaces("next"), { description = "cycle through workspaces" })
hl.bind("SUPER + SHIFT + TAB", smw.cycle_workspaces("prev"), { description = "cycle backwards through workspaces" })
hl.bind("SUPER + SHIFT + RIGHT", smw.workspace("+1"), { description = "move to next workspace" })
hl.bind("SUPER + SHIFT + LEFT", smw.workspace("-1"), { description = "move to previous workspace" })
