-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Gazelle WiFi TUI - floating window like Impala

-- Using windowrulev2 and initialClass for xdg-terminal-exec compatibility

hl.window_rule({
    name  = "float",
    match = {
        initialClass = "(Gazelle)",
    },
    float = true,
})

hl.window_rule({
    name  = "center",
    match = {
        initialClass = "(Gazelle)",
    },
    center = true,
})

hl.window_rule({
    name  = "size_800_600",
    match = {
        initialClass = "(Gazelle)",
    },
    size = "800 600",
})
